#!/usr/bin/env bash

cd "$(git rev-parse --show-toplevel)"

CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "\.java$")

if [ -z "$CHANGED_FILES" ]; then
    exit 0
fi

echo "$CHANGED_FILES" > .pmd_file_list.txt

RESULT=$(pmd check --file-list .pmd_file_list.txt --rulesets config/pmd/pmd-ruleset.xml --format text 2>&1 --no-progress --fail-on-violation)
EXIT_CODE=$?
echo "PMD exited with code=$EXIT_CODE"

rm .pmd_file_list.txt

if [ "$EXIT_CODE" -eq 0 ]; then
  echo "PMD: no violations."
    exit 0
else
  echo "PMD detected issues in code. PMD exited with code=$EXIT_CODE"
  echo "Result:"
  echo "*****************"
  echo "$RESULT"
  echo "*****************"
  echo "Commit canceled. Please fix the listed issues and try again."
  exit 1
fi

exit 0