version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Kyiv"
    open-pull-requests-limit: 20
    allow:
      - dependency-type: "direct"
    labels: [ "deps", "gradle" ]
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      spring:
        patterns:
          - "org.springframework*"
          - "org.springframework.boot*"
          - "org.springframework.security*"
      test-stack:
        patterns:
          - "org.testng*"
          - "org.assertj*"
          - "org.hamcrest*"
          - "org.mockito*"
      build-plugins:
        patterns:
          - "io.spring.dependency-management*"
          - "org.owasp.dependency-check*"
      http-json:
        patterns:
          - "com.squareup.okhttp3*"
          - "com.fasterxml.jackson*"
          - "org.apache.httpcomponents*"
      gradle-wrapper:
        patterns:
          - "gradle-wrapper"
        update-types:
          - "patch"
          - "minor"
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Kyiv"
    labels: [ "deps", "github-actions" ]
    open-pull-requests-limit: 10
