name: API tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: windows-latest

  # Steps this job must take to complete
    steps:
      # Reference the main branch. For more information visit https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@main

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
            java-version: '21'
            distribution: 'corretto'
            cache: gradle

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '20.x'

      - name: Run API tests
        run: ./gradlew clean test
      
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report
          path: api-tests/build/reports/tests/test

      - name: Publish Test Summary Results
        run: npx github-actions-ctrf ctrf/ctrf-report.json